#!/usr/bin/env bash


pandoc \
  -V lang=nl \
  --number-sections \
  --filter pandoc-fignos \
  --bibliography bib/ref.bib \
  --filter pandoc-citeproc \
  --csl=bib/apa.csl \
  -o prothesehand.pdf \
  -s 00_voorblad.md \
  01_inleiding.md \
  02_hedendaagseprotheses.md \
  03_anatomievandehand.md \
  04_materialenensoftware.md \
  05_intermedian.md \
  06_ontwerpenenprinten.md \
  07_elektronica.md \
  08_programmeren.md \
  09_conclusieendiscussie.md \
  10_bijlagereferenties.md
