#!/usr/bin/env bash

# Handles figure numbering
pandoc_fignos="--filter pandoc-fignos"

# creates the bibliography part of
bibliography="--bibliography bib/ref.bib"
csl="--csl=bib/apa.csl"

output="-o prothesehand.pdf"

source="-s prothesehand.tex"


# call the function
pandoc ${pandoc_fignos} ${bibliography} ${csl} ${output} ${source}
